# Generated by Django 5.1.4 on 2024-12-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploaded_images/')),
                ('converted_image', models.ImageField(blank=True, null=True, upload_to='converted_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
